apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  labels:
    app: gateway-server
spec:
  type: LoadBalancer
  selector:
    app: gateway-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
